# Generated by Django 3.2.12 on 2023-11-16 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
